### ISSUE TITLE
Silence in being launched locally

### ISSUE THREAD

**Issue by dfcreative** [otalk/getUserMedia#12]
Hello!
If to open a page in browser locally as `file://...`, then `getusermedia` does not invoke a callback, as if everything is fine, but indeed it is not. Should it?
I think it would be useful to catch error or something, to display that it is not available.

**Comment by fippo** [comment]
that's chrome's behaviour when called from file:// -- afaik there is no way to detect that (even though one could look for file:// in window.location.href)
