### ISSUE TITLE
why use webrtc-adapter-test?

### ISSUE THREAD

**Issue by contra** [otalk/getUserMedia#18]
we had to switch to a different getusermedia library because webrtc-adapter-test is blowing up on anything that isnt chrome or firefox, and mutating a bunch of stuff on the browser. not cool. what's the reason for using this library?

**Comment by calebboyd** [comment]
I have experienced the same issues but am able to run a fork using jspm...

**Comment by xdumaine** [comment]
Can you elaborate on what "blowing up" means?

**Comment by KaptenJansson** [comment]
I assume this https://github.com/webrtc/adapter/issues/122

**Comment by fippo** [comment]
the reasons for blowing up should be gone with webrtc-adapter-test 0.2.3 (thanks @KaptenJansson)

The reasons for using this is that I am not interested in writing or maintaining my own shim (in particular stuff like @jan-ivar's constraints transform). The road has been a little more bumpy than I expected but...

**Comment by fippo** [comment]
oh wait, this still pins adapter to 0.1.9 to avoid the double-include bug in 0.2.1.

**Comment by fippo** [comment]
uhm well.. I think the comment about the reasons being gone was too early -- another reason for blowing up is done at least.

**Comment by contra** [comment]
This is what I don't like:

https://github.com/webrtc/adapter/blob/master/adapter.js#L100

Why is a module that should just wrap getUserMedia defining a bunch of shit on the window object and mutating globals that have nothing to do with getUserMedia without my knowledge? This makes it totally incompatible with any other webrtc tooling (temasys, iosrtc, etc.)

Please rethink the way this whole ecosystem of modules is written.

**Comment by contra** [comment]
I've opened a related ticket here https://github.com/webrtc/adapter/issues/125 but even if it quits mutating the globals, I don't understand why this module needs to be using the adapter

**Comment by fippo** [comment]
go ahead and fix the issue that adapter started as a monolithic non-module three years ago. Good luck.
Mind you that in modern browsers, 90% of the code in this module is no longer needed.

**Comment by nfriedly** [comment]
@contra you might be interested in https://www.npmjs.com/package/get-user-media-promise - It's  a wrapper for the newer Promise-based `navigator.mediaDevices.getUserMedia()` API, and it's a much smaller, simpler library with no dependencies.

**Comment by fippo** [comment]
The problem solved by adapter is that Chrome still (half a year later) does not support the getusermedia constraints from the w3c spec and I have no desire to reinvent Jan-Ivar's code for this. And I have not seen anyone doing this in a way that is not a license violation.

**Comment by contra** [comment]
Maybe you should put a note in the readme that says this module only supports chrome and firefox so people don't waste their time.

**Comment by KaptenJansson** [comment]
That info can be found in the interop link on the README page but I do agree we can be more clear. I will add supported browsers to the README. Thanks for the suggestion!

It would also be useful if people could file an issue or submit a PR with a fix for the browsers they want it to work on.

**Comment by fippo** [comment]
@contra why don't you go play on your own lame copy of adapter? ktnxbye

**Comment by contra** [comment]
@KaptenJansson 100% agree on all points - I was open to submitting a PR fixing this but the response from the maintainer made it clear they were not interested in resolving it.

@fippo Lame copy of adapter? Not sure what you're talking about.

**Comment by xdumaine** [comment]
https://github.com/contra/rtc-everywhere/

Generally using a wrapper on a shim next to another shim is not going to go well. Suggest using one or the other, and if this one causes you issues, then just use your own.

**Comment by fippo** [comment]
@contra if commenting "not cool" is the way you offer a  PR...


This module is a thing of the past. Both Firefox and Edge support navigator.mediaDevices.getUserMedia natively now, Chrome soon will. This removes one reason to use the module.
The other reason was the callback-based API but navigator.mediaDevices.getUserMedia uses promises.

**Comment by contra** [comment]
@xdumaine How is rtc-everywhere a "lame copy" of the adapter? The projects aren't even comparable.

@fippo Why not note this in the README? All I'm asking for is either fix the library or mark it as deprecated. I don't understand why this issue is going back and forth, the fix is extremely simple and would take less than a minute or two to end this.

There's no reason to get heated with me and start throwing personal insults calling my projects "lame copies" like a five year old.

**Comment by fippo** [comment]
@contra: I am still looking for the concrete suggestion for a fix that fulfills constraints like being able to use spec gum constraints in browsers that don't support them.

README is not mentioning support for anything that is not a browser anywhere I can see, nor is package.json in the tags.

re lame: will file an issue over the issues I have with your project's README...

**Comment by fippo** [comment]
@contra I'd recommend not 'advising' people who maintain projects which are even remotely similar to your own unless invited to. In particular not making false pretences (Edge is supported here).

And check the timeline. You're making more false assertions.
