### ISSUE TITLE
Doesn't work in Electron

### ISSUE THREAD

**Issue by pyro2927** [otalk/getUserMedia#22]
[Electron](http://electron.atom.io/) leverages Node.JS, which has access to the navigator, but seems to be loading `index-node.js`, which just throws back an error.

**Comment by fippo** [comment]
well, index-node is mostly empty... did you try index-browser?

**Comment by pyro2927** [comment]
`require('getUserMedia')` seems to load index-node by default.  Are you suggesting doing something like `require('getUserMedia/index-browser')`?

**Comment by fippo** [comment]
yeah. odd that this behaviour is so different in electron and nw/cef

**Comment by pyro2927** [comment]
Alright, will close this then.
