### ISSUE TITLE
Access to array of cameras

### ISSUE THREAD

**Issue by DevNIX** [otalk/getUserMedia#27]
I know that it is possible to get an array of all the available cameras using some browsers like Chrome. How can I archieve it through your shim?

**Comment by fippo** [comment]
Just use the standard navigator.mediaDevices.getUserMedia API to enumerate (works in Chrome, Firefox and Edge) and then pass the deviceId as a constraint, just as shown [here](https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/munge-sdp/js/main.js#L111-L122)

**Comment by DevNIX** [comment]
I mean, then I have to stop working with this helper?

Wow, thank you for answering so fast!

**Comment by fippo** [comment]
you can still use it but the standard APIs have evolved a lot since this has been written. You still need https://github.com/webrtc/adapter which is shipped in here though :-)

**Comment by DevNIX** [comment]
Thank you! I'm working right now with that adapter, I close the issue :)
