### ISSUE TITLE
webrtc-adapter

### ISSUE THREAD

**Issue by dfcreative** [otalk/getUserMedia#29]
Hello @fippo!
Thanks for the very handy package!
One question troubles me. In `index-browser.js` there is a `webrtc-adapter` dependency, which is a sort-of polyfill. That, I believe, unresonably bloats bundle size up to 70kb(!). That is larger than size of some web-applications, and all that is only to provide a bit more convenient way to get user media than default.
How much is it reasonable?
Thanks.

**Comment by fippo** [comment]
arguably this module should be using just the GUM shims from adapter which are in separate files so its theoretically possible to require them without pulling in the rest of adapter (in particular the rather large edge peerconnection shim).

In practice, if you are using this module (and you should really be using the native (or polyfilled) APIs these day imo), you are most likely also using the peerconnection api elsewhere so the amount of unwanted code is not that big.

**Comment by dfcreative** [comment]
Reasonable, but why should we use peerconnection for web-audio-api, they are not even close.

**Comment by fippo** [comment]
if you are just interested in webaudio stuff you might not want to use this module.
Instead, i'd go for a naive shim of navigator.getUserMedia (see the README for an example) until Chrome supports navigator.mediaDevices.getUserMedia (hopefully in stable this year still)

**Comment by dfcreative** [comment]
Yes, I did so. Btw the size is not the only concern. The bundling time is also affected. For example, using budo server or watchify, especially with -g babelify or -g bubleify becomes noticeably slower. I just can't get - if the module should better be using only shims from the same adapter, what are the reasons not to do so? That is cheap improvement.

**Comment by fippo** [comment]
most things depending on this module (and mostly for legacy reasons) also use the peerconnection so this never got enough priority.

**Comment by dfcreative** [comment]
haha, nice excuse for justifying technical debt. Ok.

**Comment by dfcreative** [comment]
Thought it is not a debt in that case. Anyways close if you feel so.

**Comment by fippo** [comment]
It is. But i'd rather sit this out until we get navigator.mediaDevices.getUserMedia natively :-)
