### ISSUE TITLE
Camera is not working in Chrome

### ISSUE THREAD

**Issue by aziz4004** [otalk/getUserMedia#34]
Camera is not working in Chrome
Good: 55.0.2873.0
Bad : 55.0.2875.0

https://bugs.chromium.org/p/chromium/issues/detail?id=674608&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&start=100

**Comment by xdumaine** [comment]
@aziz4004 You'll need to be more specific about a problem you're having. That bug looks dead, and I know that both native getUserMedia and this lib are still working in 55.

**Comment by aziz4004** [comment]
Check in latest version of chrome.
I am checking on Version 56.0.2924.87 (64-bit)

**Comment by fippo** [comment]
does https://webrtc.github.io/samples/src/content/getusermedia/gum/ still work?

I am not sure what @addyosmani uses for the demo mentioned in the chrome bug but I don't think it is this library.

**Comment by aziz4004** [comment]
Not working in chrome.
browser shows that camera is in use,but no display of camera ,

and same URL is working in firefox.

**Comment by fippo** [comment]
if the camera is broken on https://webrtc.github.io/samples/src/content/getusermedia/gum/ file a chrome issue and say so. Including the information from the chrome://media-internals/ video capture tab might be very helpful.

This is not something a JS library can fix.
